---
title: "課堂練習模版"
author: "Wangyun"
date: "2020-10-28"
output: output_format
params:
  id: "410882014"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
vectorExample <- c("小明", "小英", "大雄")

# 有多少位置可選：
length(vectorExample)

vectorExample[[1]]
vectorExample[[3]]
```
```{r}
listExample <- list(student = "小明", 
                    學期 = list(`108-1` = list(list(name = "個體經濟學",
                                              
    teacher = "Alice", grade = 85)), `108-2` = list(list(name = "總體經濟學", 
    teacher = "Mark", grade = 78))))
# 有多少位置可選：
str(listExample)
str(listExample, 2)
length(listExample)# 第一層基本元素架構
listExample[[1]]
listExample[[2]]


```

```{r}
vectorExample
vectorExample[c(1, 3)]

```

`
# 顯示到第一層
```{r}
# 顯示到第一層
str(listExample, max.level = 1)

listExample[[2]]

```
```{r}
numVector <- c(2, 3, 6, -1, 4, 2, 6)
select1 <- numVector[c(1, 4)]
select1
select2 <- select1[[1]]
select2

# 相當於
numVector[c(1, 4)][[1]]
```

```{r}
select1 <- numVector[c(T, T, F, T, F, F, T)]
select1
select2 <- select1[c(1, 4)]
select2

# 相當於
numVector[c(T, T, F, T, F, F, T)][c(1, 4)]
```




```{r}
majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
names <- c("小英", "小美", "大雄", "阿華", "阿尼")
gender <- c("F", "F", "M", "F", "M")
pickEcon<-majors=="經濟學系"
pickEcon<-c(T,T,F,F,T)
names<-(pickEcon)
majors
pickEcon


which(majors=="經濟學系") -> test_Econ
majors[test_Econ]
majors[which(majors=="經濟學系")]
names[majors=="經濟學系"]
names[c(pickEcon)]

```

```{r}
majors <- c("經濟學系", "經濟學系", "社會學系", "社工系", "經濟學系")
names <- c("小英", "小美", "大雄", "阿華", "阿尼")
names[majors=="經濟學系"]

```





```{r}
today <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))
tomorrow <- list(list("台北市", c(highest_temp = 25), c(lowest_temp = 18)), list("新北市", 
    c(highest_temp = 24), c(lowest_temp = 15)))

weather <- list(today, tomorrow)

print(weather)
str(weather)
 
```


